### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by woubuc** [cloudflare/binary-install#1]
On Linux (Ubuntu WSL) this package works perfectly, but on Windows I get an error when I try to run the binary.

The console output:
```
> npm i -g wasm-pack
C:\Program Files\nodejs\wasm-pack -> C:\Program Files\nodejs\node_modules\wasm-pack\run.js

> wasm-pack@0.8.1 postinstall C:\Program Files\nodejs\node_modules\wasm-pack
> node -e 'require("./binary.js").install()'

+ wasm-pack@0.8.1
added 35 packages from 22 contributors in 4.136s


> wasm-pack --help
fs.js:127
    throw err;
    ^

Error: ENOENT: no such file or directory, mkdir 'C:\Users\Wouter\AppData\Roaming\wasm-pack-nodejs\Config'
    at mkdirSync (fs.js:806:3)
    at Binary._getInstallDirectory (C:\Users\Wouter\AppData\Roaming\nvm\v12.9.1\node_modules\wasm-pack\node_modules\binary-install\src\binary.js:48:7)
    at Binary._getBinaryDirectory (C:\Users\Wouter\AppData\Roaming\nvm\v12.9.1\node_modules\wasm-pack\node_modules\binary-install\src\binary.js:54:35)
    at Binary._getBinaryPath (C:\Users\Wouter\AppData\Roaming\nvm\v12.9.1\node_modules\wasm-pack\node_modules\binary-install\src\binary.js:66:36)
    at Binary.run (C:\Users\Wouter\AppData\Roaming\nvm\v12.9.1\node_modules\wasm-pack\node_modules\binary-install\src\binary.js:122:29)
    at run (C:\Users\Wouter\AppData\Roaming\nvm\v12.9.1\node_modules\wasm-pack\binary.js:33:10)
    at Object.<anonymous> (C:\Users\Wouter\AppData\Roaming\nvm\v12.9.1\node_modules\wasm-pack\run.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32) {
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: 'C:\\Users\\Wouter\\AppData\\Roaming\\wasm-pack-nodejs\\Config'
}
```

On Linux it also logs these lines during install, but they don't appear on Windows:
```
Downloading release ...
wasm-pack has been installed!
```

I double checked and I'm using the exact same commands on both systems. On Linux, instead of the error it shows me the help info as expected.

The error occured when trying to implement `binary-install` for my own package, but then I verified that it also happens with the latest published version of `wasm-pack` on npm.

**Comment by woubuc** [comment]
I checked out the code, it seems that you're trying to create multiple directories at once.

The path `C:\Users\Wouter\AppData\Roaming` exists, but `fs.mkdir` can only create one directory at a time, so it errors when trying to create the full path `C:\Users\Wouter\AppData\Roaming\wasm-pack-nodejs\Config`.

This can probably be solved by using [mkdirp](https://www.npmjs.com/package/mkdirp).
